const mongoose=require('mongoose');
const feedbackSchema=new mongoose.Schema({
    interviewId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Interview',
        required:true
    },
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    overallScore:{
        type:Number,
        min:0,
        max:10
    },
    totalQuestionsAsked:{
        type:Number,
        default:0,
    },
    scoresByTopic:[{
        topic:{type:String},
        score:{type:Number}
    },],
    summary:{
        type:String
    },
    strengths:{
        type:[String],
        default:[],
    },
    weaknesses:{
        type:[String],
        default:[],
    },
    verdict:{
        type:String,
        enum:["Hire","No Hire","Pending"],
        default:"Pending",
    },
    createdAt:{
        type:Date,
        default:Date.now,
    },
});
module.exports=mongoose.model('Feedback',feedbackSchema);