const mongoose=require('mongoose');
const interviewSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    role:{
        type:String,
        required:true,
        enum:['frontend','backend','devops','datascientist','dataanalyst','fullstack-devloper']
    },
    difficulty:{
        type:String,
        required:true,
        enum:['junior','mid','senior']
    },
    status:{
        type:String,
        enum:['active','completed','abandoned'],
        default:'active'
    },
    transcript:[{
        sender:{
            type:String,
            enum:['ai','user'],
            required:true
        },
        content:{
            type:String,
            required:true
        },
        timestamp:{
            type:Date,
            default:Date.now
        },
        metadata:{
            type:{type:String},
            questionId:String
        }
    }],
    startTime:{
        type:Date,
        default:Date.now
    },
    endTime:{
        type:Date
    }
});
module.exports=mongoose.model('Interview',interviewSchema);