const mongoose=require('mongoose');
const interviewSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    agentSessionId:{
        type:String,
        required:true,
    },
    role:{
        type:String,
        required:true,
        enum:[
            'frontend',
            'backend',
            'devops',
            'fullstack-developer',
            'data-analyst',
            'data-scientist',
            'ml-engineer',
            'genai-engineer',
            'app-developer',
            'cybersecurity-engineer',
            'blockchain-developer'
        ]
    },
    difficulty:{
        type:String,
        required:true,
        enum:['junior','mid','senior']
    },
    status:{
        type:String,
        enum:['active','completed','abandoned'],
        default:'active'
    },
    resumeContext:{
        type:Object,
        default:null,
    },
    transcript:[{
        sender:{
            type:String,
            enum:['ai','user'],
            required:true
        },
        content:{
            type:String,
            required:true
        },
        timestamp:{
            type:Date,
            default:Date.now
        },
        metadata:{
            type:Object,
            questionId:String
        },
    },],
    startTime:{
        type:Date,
        default:Date.now
    },
    endTime:{
        type:Date
    }
});
module.exports=mongoose.model('Interview',interviewSchema);
